name: magic_express_delivery
description: Mobile Application for Magic Express Delivery
publish_to: 'none' 
version: 1.0.0+3

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  bloc: ^7.0.0
  flutter_bloc: ^7.1.0
  flutter_typeahead: ^3.1.1
  flutter_simple_dependency_injection: ^2.0.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  equatable: ^2.0.0
  intl: ^0.17.0
  dartz: ^0.10.0-nullsafety.2
#  super_enum: ^0.5.0
  dio: ^4.0.0
  http_parser: ^4.0.0
  shared_preferences: ^2.0.5
  email_validator: '^2.0.1'
  quiver: ^3.0.1
  formz: ^0.4.0
  flow_builder: ^0.0.2
  very_good_analysis: ^2.1.0
  repositories:
    path: packages/repositories
  services:
    path: packages/services

dev_dependencies:
#  super_enum_generator: ^0.6.0
  build_runner: ^1.7.1
  flutter_native_splash: ^1.2.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/dispatch_rider.png
    - assets/shopping_cart.png
    - assets/banner.png
