name: services
description: Dart package which contains the services to the network APIs.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  meta: ^1.3.0
  very_good_analysis: ^2.1.0
  dio: ^4.0.0
  http_parser: ^4.0.0
  shared_preferences: ^2.0.5
